# Generated by Django 2.0.3 on 2018-03-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibleYn',
            field=models.BooleanField(default=True),
        ),
    ]
